<?php

declare(strict_types=1);

namespace Atendwa\Support\Concerns\Models;

use Illuminate\Database\Eloquent\Model;
use Throwable;

trait HasAutoGeneratedSlug
{
    public function getRouteKeyName(): string
    {
        return self::slugColumn();
    }

    /**
     * @throws Throwable
     */
    protected static function bootHasAutoGeneratedSlug(): void
    {
        static::creating(
            fn (Model $model) => $model->setAttribute(self::slugColumn(), nextModelSlug($model, self::prefix($model)))
        );
    }

    protected static function prefix(Model $model): string
    {
        return modelInitials($model) . self::slugDelimiter();
    }

    protected static function slugDelimiter(): string
    {
        return '-';
    }

    protected static function slugColumn(): string
    {
        return 'slug';
    }
}
